In [2]:
import sys; sys.path.append('../..')
from abslithist import *

In [22]:
PATH_PSGS = os.path.join(PATH_DATA, 'counts', 'data.absconc.CanonFiction.psgs.v7.csv.gz')
# PATH_PSGS = '/Users/ryan/DH/data/data_abslithist/psgs/data.psgs.CanonFiction.v4.v2.jsonl'

In [23]:
df = pd.read_csv(PATH_PSGS)
df

,id,slice,source,period,num_abs,num_conc,num_neither,num_total,num_types,passage
0,Homer.Odyssey.Butler,1,Median,median,16,11,73,100,90,<i>BOOK</i> I\n<br>\n<br>\n<br> THE GODS IN...
1,Homer.Odyssey.Butler,2,Median,median,12,21,67,100,92,that keep <i>heaven</i> and <i>earth</i>\n...
2,Homer.Odyssey.Butler,3,Median,median,4,32,64,100,87,and pages were <i>bustling</i> about to ...
3,Homer.Odyssey.Butler,4,Median,median,8,21,71,100,90,"over their <i>hands</i>, <i>maids</i>\n<br>..."
4,Homer.Odyssey.Butler,5,Median,median,14,10,76,100,91,"in <i>mid</i> <i>ocean</i>,\n<br> or a <i>..."
...,...,...,...,...,...,...,...,...,...,...
540666,Ferrante.Neapolitan Novels,1339,Median,median,21,2,77,100,92,like that: when I don't <i><b>submit</b><...
540667,Ferrante.Neapolitan Novels,1340,Median,median,16,7,77,100,90,"would <i><b>continue</b></i> <i>forever</i>,..."
540668,Ferrante.Neapolitan Novels,1341,Median,median,25,12,63,100,95,<i>assigned</i> <i>prizes</i> to the most ...
540669,Ferrante.Neapolitan Novels,1342,Median,median,13,16,71,100,90,"with the Labrador I got recently, I <i>..."
540670,Ferrante.Neapolitan Novels,1343,Median,median,15,9,69,93,73,.\n<br>\n<br> Or maybe not. Maybe those t...

In [31]:
row = df.sample(1).iloc[0]
print(row)
printm(row.passage)

id                                   Thucydides.PeloponnesianWar
slice                                                        195
source                                                    Median
period                                                    median
num_abs                                                       26
num_conc                                                      13
num_neither                                                   61
num_total                                                    100
num_types                                                     90
passage        its  <i>deformity</i>.  However,  if\n<br> <i>...
Name: 2839, dtype: object

its  <i>deformity</i>.  However,  if
<br> <i>leading</i>  <i><b>powers</b></i>  were  to  do  what  you  are  now  doing,  and  <i>putting</i>  one  <i>short</i>
<br> <i><b>question</b></i>  to  all  <i>alike</i>  were  to  <i><b>decide</b></i>  accordingly,  men  would  be  less
<br> <i><b>tempted</b></i>  to  <i>seek</i>  <i><u>fine</u></i>  <i>phrases</i>  to  <i><u>cover</u></i>  bad  <i><b>actions</b></i>."
<br>
<br> Such  were  the  words  of  the  Thebans.  The  Lacedaemonian  <i><b>judges</b></i>  <i><b>decided</b></i>
<br> that  the  <i><b>question</b></i>  whether  they  had  <i>received</i>  any  <i>service</i>  from  the
<br> Plataeans  in  the  <i>war</i>,  was  a  <i>fair</i>  one  for  them  to  put;  as  they  had
<br> always  <i>invited</i>  them  to  be  <i>neutral</i>,  <i>agreeably</i>  to  the  <i><b>original</b></i>  <i><b>covenant</b></i>  of
<br> <i>Pausanias</i>  after  the  <i><b>defeat</b></i>  of  the  <i>Mede</i>,  and  had  again  definitely  <i>offered</i>
<br> them  the  same  <i><b>conditions</b></i>  before  the  <i>blockade</i>.  This  <i>offer</i>  having
<br> been  <i>refused</i>,  they  were  now,  they  <i><b>conceived</b></i>,  by  the  <i><b>loyalty</b></i>  of  their
<br> <i><b>intention</b></i>  <i>released</i>  from  their  <i><b>covenant</b></i>;  and  having,  as  they  <i><b>considered</b></i>,
<br> <i><b>suffered</b></i>  <i><b>evil</b></i>  at  the  <i>hands</i>  of  the  Plataeans,  they  brought  them  in  again
<br> one  by  one  and  <i>asked</i>  each  of  them  the  same  <i><b>question</b></i>,  that  is  to  say,
<br> whether  they  had  done  the  Lacedaemonians  and  <i>allies</i>  any  <i>service</i>  in  the
<br> <i>war</i>;  and  upon  their  saying  that  they  had  not,  took  them  out  and  <i>slew</i>
<br> them,  all  without  <i><b>exception</b></i>.  The  <i>number</i>  of  Plataeans  thus  <i>massacred</i>  was
<br> not  less  than  two  hundred,  with  twenty- five  Athenians  who  had  <i>shared</i>  in
<br> the  <i>siege</i>.  The  women  were  taken  as  <i>slaves</i>.  The  <i>city</i>  the  Thebans  gave
<br> for  about  a  year  to  some  <i><b>political</b></i>  <i>emigrants</i>  from  Megara  and  to  the
<br> <i>surviving</i>  Plataeans  of  their  own  <i>party</i>  to  <i>inhabit</i>,  and  afterwards  <i>razed</i>
<br> it  to  the  <i>ground</i>  from  the  very  <i>foundations</i>,  and  <i>built</i>  on  to  the  <i>precinct</i>
<br> of  <i>Hera</i>  an  <i>inn</i>  two  hundred  <i><u>feet</u></i>  <i><u>square</u></i>,  with  <i>rooms</i>  all  <i><u>round</u></i>  above
<br> and  below,  making  use  for  this  <i>purpose</i>  of  the  <i><u>roofs</u></i>  and  <i>doors</i>  of  the
<br> Plataeans:  of  the  <i>rest</i>  of  the  <i>materials</i>  in  the  <i><u>wall</u></i>,  the  <i><u>brass</u></i>  and  the
<br> <i><u>iron</u></i>,  they  made  <i><u>couches</u></i>  which  they  <i>dedicated</i>  to  <i>Hera</i>,  for  whom  they  also
<br> <i>built</i>  a  <i><u>stone</u></i>  <i>chapel</i>  of  a  hundred  <i><u>feet</u></i>  <i><u>square</u></i>.  The  <i>land</i>  they  <i>confiscated</i>
<br> and  let  out  on  a  ten  years'  <i>lease</i>  to  Theban  <i>occupiers</i>.  The  <i><b>adverse</b></i>
<br> <i><b>attitude</b></i>  of  the  Lacedaemonians  in  the  whole  Plataean  <i><b>affair</b></i>  was  mainly
<br> <i><b>adopted</b></i>  to  please  the  Thebans,  who  were  thought  to  be  useful  in  the  <i>war</i>
<br> at  that  moment  <i>raging</i>.  Such  was  the  end  of  Plataea,  in  the  ninety- third
<br> year  after  she  became  the  <i>ally</i>  of  Athens.
<br>
<br> Meanwhile,  the  forty  <i>ships</i>

In [32]:
printm("""from  me  the  cry,
<br>
<br>" How  little  anything  is  <i>changed</i>  here!"
<br>
<br> We  <i>stopped</i>  again  at  Abingdon,  which,  like  Wallingford,
<br>
<br> was  in  a  way  both  old  and  new  to  me,  since  it
<br>
<br> had  been  <i>lifted</i>  out  of  its  nineteenth- <i>century</i>  <i><b>degradation</b></i>,
<br>
<br> and  otherwise  was  as  little  <i>altered</i>  as  might  be.
<br>
<br> <i><u>Sunset</u></i>  was  in  the  <i><u>sky</u></i>  as  we  <i><u>skirted</u></i>  Oxford  by
<br>
<br> Oseney;  we  <i>stopped</i>  a  <i>minute</i>  or  two  <i>hard</i>  by  the
<br>
<br> <i>ancient</i>  <i>castle</i>  to  put  Henry  Morsom  <i><u>ashore</u></i>.  It  was
<br>
<br> a  matter  of  course  that  so  far  as  they  could  be  seen
<br>
<br> from  the  <i><u>river</u></i>,  I  <i>missed</i>  none  of  the  <i><u>towers</u></i>  and  <i><u>spires</u></i>
<br>
<br> of  that  once  don- beridden  <i>city</i>;  but  the  <i><u>meadows</u></i>  all
<br>
<br> <i><u>round</u></i>,  which,  when  I  had  last  <i>passed</i>  through  them,
<br>
<br> were  getting  <i>daily</i>  more  and  more  <i>squalid</i>,  more  and
<br>
<br> more  <i><b>impressed</b></i>  with  the  <i>seal</i>  of  the " <i>stir</i>  and  <i><b>intellectual</b></i>
<br>
<br> life  of  the  nineteenth  <i>century</i>,"  were  no  <i>longer</i>
<br>
<br> <i><b>intellectual</b></i>,  but  had  once  again  become  as  <i>beautiful</i>
<br>
<br> as  they  should  be,  and  the  little  <i><u>hill</u></i>  of  Hinksey,  with
<br>
<br> two  or  three  very  <i>pretty</i>  <i><u>stone</u></i>  <i>houses</i>  new- <i>grown</i>  on  it
<br>
<br> (I  use  the  word  <i><b>advisedly</b></i>;  for  they  seemed  to  <i>belong</i>
<br>
<br> to  it)  <i>looked</i>  down  <i>happily</i>  on  the  full  <i>streams</i>  and
<br>
<br> <i><u>waving</u></i>  <i><u>grass</u></i>,  <i><u>grey</u></i>  now,  but  for  the  <i><u>sunset</u></i>,  with  its
<br>
<br> <i>fast</i>- <i>ripening</i>  <i>seeds</i>.
<br>
<br> The  <i>railway</i>  having  <i>disappeared</i>,  and  <i>therewith</i>  the
<br>
<br> various  <i>level</i>  <i>bridges</i>  over  the  <i>streams</i>  of  Thames,  we
<br>
<br> were  soon  through  <i>Medley</i>  <i><u>Lock</u></i>  and  in  the  <i>wide</i>
<br>
<br> <i><u>water</u></i>  that  <i><u>washes</u></i>  <i>Port</i>  <i><u>Meadow</u></i>,  with  its  <i>numerous</i>
<br>
<br> <i>population</i>  of  <i><u>geese</u></i>  <i><b>nowise</b></i>  <i>diminished</i>;  and  I  thought
<br>
<br> with  interest  how  its  name  and  use  had  <i>survived</i>  from
<br>
<br> the  <i>older</i>  <i><b>imperfect</b></i>  <i>communal</i>  <i>period</i>,  through  the
<br>
<br> time  of  the  <i>confused</i>  <i><b>struggle</b></i>  and  <i><b>tyranny</b></i>  of  the  <i><b>rights</b></i>
<br>
<br> of  <i>property</i>,  into  the  present  <i>rest</i>  and  <i><b>happiness</b></i>  of
<br>
<br> <i>complete</i>  <i><b>Communism</b></i>.
<br>
<br> I  was  taken  <i><u>ashore</u></i>  again  at  Godstow,  to  see  the
<br>
<br> <i>remains</i>  of  the  old  <i>nunnery</i>,  <i>pretty</i>  nearly  in  the  same
<br>
<br> <i><b>condition</b></i>  as  I  had  <i>remembered</i>  them;  and  from  the
<br>
<br> <i>high</i>  <i><u>bridge</u></i>  over  the  <i><u>cut</u></i>  <i>close</i>  by,  I  could  see,  even
<br>
<br> in  the  <i>twilight</i>,  how  <i>beautiful</i>  the  little  <i>village</i>  with  its
<br>
<br> <i><u>grey</u></i>  <i><u>stone</u></i>  <i>houses</i>  had  become;  for  we  had  now  come
<br>
<br> into  the  <i><u>stone</u></i>- country,  in  which  every  <i>house</i>""")

from  me  the  cry,
<br>
<br>" How  little  anything  is  <i>changed</i>  here!"
<br>
<br> We  <i>stopped</i>  again  at  Abingdon,  which,  like  Wallingford,
<br>
<br> was  in  a  way  both  old  and  new  to  me,  since  it
<br>
<br> had  been  <i>lifted</i>  out  of  its  nineteenth- <i>century</i>  <i><b>degradation</b></i>,
<br>
<br> and  otherwise  was  as  little  <i>altered</i>  as  might  be.
<br>
<br> <i><u>Sunset</u></i>  was  in  the  <i><u>sky</u></i>  as  we  <i><u>skirted</u></i>  Oxford  by
<br>
<br> Oseney;  we  <i>stopped</i>  a  <i>minute</i>  or  two  <i>hard</i>  by  the
<br>
<br> <i>ancient</i>  <i>castle</i>  to  put  Henry  Morsom  <i><u>ashore</u></i>.  It  was
<br>
<br> a  matter  of  course  that  so  far  as  they  could  be  seen
<br>
<br> from  the  <i><u>river</u></i>,  I  <i>missed</i>  none  of  the  <i><u>towers</u></i>  and  <i><u>spires</u></i>
<br>
<br> of  that  once  don- beridden  <i>city</i>;  but  the  <i><u>meadows</u></i>  all
<br>
<br> <i><u>round</u></i>,  which,  when  I  had  last  <i>passed</i>  through  them,
<br>
<br> were  getting  <i>daily</i>  more  and  more  <i>squalid</i>,  more  and
<br>
<br> more  <i><b>impressed</b></i>  with  the  <i>seal</i>  of  the " <i>stir</i>  and  <i><b>intellectual</b></i>
<br>
<br> life  of  the  nineteenth  <i>century</i>,"  were  no  <i>longer</i>
<br>
<br> <i><b>intellectual</b></i>,  but  had  once  again  become  as  <i>beautiful</i>
<br>
<br> as  they  should  be,  and  the  little  <i><u>hill</u></i>  of  Hinksey,  with
<br>
<br> two  or  three  very  <i>pretty</i>  <i><u>stone</u></i>  <i>houses</i>  new- <i>grown</i>  on  it
<br>
<br> (I  use  the  word  <i><b>advisedly</b></i>;  for  they  seemed  to  <i>belong</i>
<br>
<br> to  it)  <i>looked</i>  down  <i>happily</i>  on  the  full  <i>streams</i>  and
<br>
<br> <i><u>waving</u></i>  <i><u>grass</u></i>,  <i><u>grey</u></i>  now,  but  for  the  <i><u>sunset</u></i>,  with  its
<br>
<br> <i>fast</i>- <i>ripening</i>  <i>seeds</i>.
<br>
<br> The  <i>railway</i>  having  <i>disappeared</i>,  and  <i>therewith</i>  the
<br>
<br> various  <i>level</i>  <i>bridges</i>  over  the  <i>streams</i>  of  Thames,  we
<br>
<br> were  soon  through  <i>Medley</i>  <i><u>Lock</u></i>  and  in  the  <i>wide</i>
<br>
<br> <i><u>water</u></i>  that  <i><u>washes</u></i>  <i>Port</i>  <i><u>Meadow</u></i>,  with  its  <i>numerous</i>
<br>
<br> <i>population</i>  of  <i><u>geese</u></i>  <i><b>nowise</b></i>  <i>diminished</i>;  and  I  thought
<br>
<br> with  interest  how  its  name  and  use  had  <i>survived</i>  from
<br>
<br> the  <i>older</i>  <i><b>imperfect</b></i>  <i>communal</i>  <i>period</i>,  through  the
<br>
<br> time  of  the  <i>confused</i>  <i><b>struggle</b></i>  and  <i><b>tyranny</b></i>  of  the  <i><b>rights</b></i>
<br>
<br> of  <i>property</i>,  into  the  present  <i>rest</i>  and  <i><b>happiness</b></i>  of
<br>
<br> <i>complete</i>  <i><b>Communism</b></i>.
<br>
<br> I  was  taken  <i><u>ashore</u></i>  again  at  Godstow,  to  see  the
<br>
<br> <i>remains</i>  of  the  old  <i>nunnery</i>,  <i>pretty</i>  nearly  in  the  same
<br>
<br> <i><b>condition</b></i>  as  I  had  <i>remembered</i>  them;  and  from  the
<br>
<br> <i>high</i>  <i><u>bridge</u></i>  over  the  <i><u>cut</u></i>  <i>close</i>  by,  I  could  see,  even
<br>
<br> in  the  <i>twilight</i>,  how  <i>beautiful</i>  the  little  <i>village</i>  with  its
<br>
<br> <i><u>grey</u></i>  <i><u>stone</u></i>  <i>houses</i>  had  become;  for  we  had  now  come
<br>
<br> into  the  <i><u>stone</u></i>- country,  in  which  every  <i>house</i>

In [21]:
df = pd.read_pickle('/Users/ryan/github/abslithist/data/scores/data.scores.CanonFiction.v2.pkl')
df

              Abs-Conc.LSN-Hapt.C16  Abs-Conc.LSN-Imag.C16  \
genre   year
Fiction 1686              -1.210993              -2.363414
        1686              -1.215972              -2.331686
        1686              -1.219092              -2.341713
        1686              -1.245807              -2.329389
        1686              -1.208295              -2.324295
...                             ...                    ...
        1619               6.701320               7.101756
        1619               6.657589               7.125289
        1619               6.684838               7.024269
        1619               6.592643               7.010001
        1619               6.809816               7.183005

              Abs-Conc.MRC-Conc.C16  Abs-Conc.MRC-Imag.C16  \
genre   year
Fiction 1686              -2.329620              -1.118934
        1686              -2.339642              -1.135342
        1686              -2.326780              -1.131346
        1686              -2.334728              -1.159935
        1686              -2.322333              -1.121806
...                             ...                    ...
        1619               6.417931               7.399289
        1619               6.404252               7.419181
        1619               6.372974               7.396690
        1619               6.300086               7.274910
        1619               6.501776               7.525959

              Abs-Conc.MT-Conc.C16  Abs-Conc.Median.C16  \
genre   year
Fiction 1686             -2.967004            -2.305375
        1686             -2.965702            -2.302349
        1686             -2.953037            -2.301252
        1686             -2.957062            -2.305611
        1686             -2.963546            -2.297188
...                            ...                  ...
        1619              5.065114             6.205167
        1619              5.055981             6.195149
        1619              4.999550             6.158054
        1619              4.965133             6.099968
        1619              5.127688             6.293607

              Abs-Conc.PAV-Conc.C16  Abs-Conc.PAV-Imag.C16  \
genre   year
Fiction 1686              -2.219567              -1.407330
        1686              -2.234267              -1.419491
        1686              -2.223788              -1.402814
        1686              -2.228012              -1.425002
        1686              -2.217914              -1.397727
...                             ...                    ...
        1619               6.829478               7.627690
        1619               6.824983               7.680713
        1619               6.790635               7.607776
        1619               6.718902               7.516154
        1619               6.914150               7.737368

              Abs-Conc.LSN-Hapt.C17  Abs-Conc.LSN-Imag.C17  ...  \
genre   year                                                ...
Fiction 1686              -1.657846              -2.597214  ...
        1686              -1.655868              -2.586726  ...
        1686              -1.619751              -2.566030  ...
        1686              -1.652054              -2.552540  ...
        1686              -1.598474              -2.534701  ...
...                             ...                    ...  ...
        1619               6.141138               6.339026  ...
        1619               6.096441               6.330341  ...
        1619               6.175398               6.326932  ...
        1619               6.097377               6.298279  ...
        1619               6.224384               6.395509  ...

              Abs-Conc.MRC-Conc.orig  Abs-Conc.MRC-Imag.orig  \
genre   year
Fiction 1686               -2.033916                0.028397
        1686               -2.076219                0.086086
        1686               -2.084294                0.091472
        1686               -2.109886               -0.093688
        1686               -2.160489                0.036708
...                              ...                     ...
        1619                5.435785                7.763466
        1619                5.825974                8.012755
        1619                5.930038                8.298650
        1619                5.794904                7.962109
        1619                5.834609                8.225189

              Abs-Conc.MT-Conc.orig  Abs-Conc.PAV-Conc.orig  \
genre   year
Fiction 1686              -0.906934               -5.786252
        1686              -0.994034               -5.983268
        1686              -0.898002               -6.164373
        1686              -1.024689               -5.510344
        1686              -0.934143               -6.217860
...                             ...                     ...
        1619               6.694009                8.805678
        1619               6.914097                8.607026
        1619               7.061188                8.453092
        1619               6.912344                9.375293
        1619               6.879739                9.197699

              Abs-Conc.PAV-Imag.orig  Abs-Conc.Median.orig  num_words  \
genre   year
Fiction 1686               -2.646450             -0.863990     4655.0
        1686               -2.641764             -0.905745     4655.0
        1686               -2.754064             -0.840450     4655.0
        1686               -2.897840             -0.981044     4655.0
        1686               -2.811964             -0.935416     4655.0
...                              ...                   ...        ...
        1619               10.846101              4.408812     7011.0
        1619               10.663976              4.541256     7011.0
        1619               10.448815              4.716740     7011.0
        1619               11.586962              4.545084     7011.0
        1619               11.459853              4.600766     7011.0

              num_words_smpl  num_texts  \
genre   year
Fiction 1686         10000.0        1.0
        1686         10000.0        1.0
        1686         10000.0        1.0
        1686         10000.0        1.0
        1686         10000.0        1.0
...                      ...        ...
        1619         10000.0        1.0
        1619         10000.0        1.0
        1619         10000.0        1.0
        1619         10000.0        1.0
        1619         10000.0        1.0

                                                          words
genre   year
Fiction 1686  evil, considerative, evident, wit, fear, desir...
        1686  seated, strayed, strokes, soonest, falling, as...
        1686  superannuated, burden, measures, sacred, scarc...
        1686  alarms, ensnare, absence, ill, desire, fain, f...
        1686  glad, answer, perceive, power, glory, alarms, ...
...                                                         ...
        1619  jasper, river, lion, herbs, singed, set, opini...
        1619  hurt, blue, canoes, island, ensued, lying, sou...
        1619  fretted, lower, hung, sailed, desired, east, w...
        1619  calm, ropes, weapons, ragged, hoist, taste, wi...
        1619  sea, willingly, ancients, entered, wood, dock,...

[3320 rows x 60 columns]