In [1]:
import sys;sys.path.append('../..')
from abslithist import *

In [2]:
df=pd.read_csv(os.path.expanduser('~/lltk_data/corpora/hathi_englit/metadata.csv'))
# df=df[df.title.str.lower().str.contains('essay')]
df['year'] = pd.to_numeric(df['imprintdate'], errors='coerce')
df['decade'] = df.year//10*10
df.decade.value_counts()

decade
1910.0    33871
1900.0    32007
1890.0    23661
1880.0    14705
1920.0    10840
1870.0     9402
1860.0     7726
1850.0     7553
1840.0     5622
1830.0     5364
1820.0     5142
1810.0     2951
1800.0     2336
1790.0      965
1770.0      651
1780.0      617
1760.0      442
1750.0      274
1730.0      136
1720.0      133
1740.0      114
1710.0       76
1700.0       37
1930.0       13
1960.0        5
1600.0        3
1950.0        3
1690.0        3
1980.0        2
1630.0        2
1940.0        1
1680.0        1
1580.0        1
1570.0        1
1970.0        1
1670.0        1
Name: count, dtype: int64

In [3]:
norm_d = get_norm_dict()
# norm_d

In [4]:
def score_freqs(path_json):
    with open(path_json) as f:
        freqs = json.load(f)
    out = []
    for word,count in freqs.items():
        if word in norm_d:
            for n in range(count):
                out.append(norm_d[word])
    return np.mean(out)

In [5]:
folder = os.path.expanduser('~/lltk_data/corpora/hathi_englit/freqs/')
folder

'/Users/ryan/lltk_data/corpora/hathi_englit/freqs/'

In [6]:
def score_freqs_folder(folder, total=None):
    out = []
    iterr = tqdm(total=total)
    for root,dirs,files in os.walk(folder):
        for file in files:
            if file.endswith('.json'):
                iterr.update(1)
                path_json = os.path.join(root,file)
                try:
                    score = score_freqs(path_json)
                    out.append({'id':path_json.replace(folder,'').replace('.json',''), 'score':score})
                except:
                    print(f'Error: {path_json}')
    return pd.DataFrame(out)

In [7]:
df_scores = score_freqs_folder(folder, total=len(df))
df_scores

  0%|          | 0/178381 [00:00<?, ?it/s]

  5%|▍         | 8481/178381 [00:46<15:05, 187.71it/s]

Error: /Users/ryan/lltk_data/corpora/hathi_englit/freqs/njp/321/01063584070.json

  5%|▍         | 8762/178381 [00:47<16:35, 170.34it/s]

Error: /Users/ryan/lltk_data/corpora/hathi_englit/freqs/njp/321/01072901539.json

  8%|▊         | 13575/178381 [01:02<12:46, 215.11it/s]

Error: /Users/ryan/lltk_data/corpora/hathi_englit/freqs/uc2/ark/+=13960=t8df6zg9p.json

 10%|▉         | 17268/178381 [01:19<13:13, 202.99it/s]

Error: /Users/ryan/lltk_data/corpora/hathi_englit/freqs/uc2/ark/+=13960=t3zs2ks5r.json

 13%|█▎        | 22634/178381 [01:50<15:59, 162.32it/s]

Error: /Users/ryan/lltk_data/corpora/hathi_englit/freqs/pst/000/028736325.json

 15%|█▍        | 26745/178381 [02:16<14:00, 180.42it/s]

Error: /Users/ryan/lltk_data/corpora/hathi_englit/freqs/nyp/334/33074375415.json

 16%|█▌        | 28955/178381 [02:29<12:52, 193.37it/s]

                               id     score
0                  chi/102/242609  0.220862
1                  chi/086/546157  0.819135
2                  chi/086/565931  0.061169
3                   chi/298/77569 -0.085700
4      uiuo/ark/+=13960=t9n30cc0p -0.322969
...                           ...       ...
28944            nnc1/cr0/0296333 -0.033678
28945            nnc1/cr0/0261335  0.062010
28946            nnc1/cr0/0261289 -0.085778
28947            nnc1/cr0/0261378 -0.014387
28948            nnc1/cr0/0325899 -0.148373

[28949 rows x 2 columns]

In [9]:
odf=df_scores.dropna().merge(df, on='id', how='left').set_index('id').sort_values('score',ascending=False)
odf

,score,_llp_,author,corpus,date,datetype,enddate,englishpct,enumcron,genre,...,oclc,place,prob80precise,recordid,startdate,subjects,title,totalpages,year,decade
id,,,,,,,,,,,,,,,,,,,,,
pst/000/057678948,1.420143,hathi_englit|pst/000/057678948,"Muir, J. B.",HathiEngLit,1890,s,,1.000,30 71-7,Drama,...,80128280.0,xx,0.75,9420151,1890,NaN,"Raciana, or, Raiders' colours of the royal, fo...",218,1890.0,1890.0
uva/x00/2031227,1.177608,hathi_englit|uva/x00/2031227,NaN,HathiEngLit,1874,s,,0.998,NaN,Fiction,...,19995629.0,nyu,0.77,9780010,1874,Readers (Primary),"Little Annie's first book, chiefly in words of...",144,1874.0,1870.0
nnc1/cu5/0518151,1.163696,hathi_englit|nnc1/cu5/0518151,"Hall, Townshend M.",HathiEngLit,1868,s,,0.983,NaN,Drama,...,34976560.0,enk,0.71,8423743,1868,England;Mineralogy,Mineralogist's directory;,200,1868.0,1860.0
coo/319/24001671233,1.052009,hathi_englit|coo/319/24001671233,NaN,HathiEngLit,1922,s,,0.996,NaN,Drama,...,5766593.0,mbc,0.68,9072946,1922,Botany;Manitoba,Check list of Manitoba flora [with notes],44,1922.0,1920.0
mdp/390/15006823200,1.031468,hathi_englit|mdp/390/15006823200,"Groth, Benno Humbert Alfred,",HathiEngLit,1911,s,,1.000,NaN,Drama,...,3721347.0,pau,0.69,2099596,1911,Sweet potatoes,The sweet potato,246,1911.0,1910.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
nnc1/100/2277352,-0.846224,hathi_englit|nnc1/100/2277352,"Greg, Percy,",HathiEngLit,1878,s,,0.999,v.2,Fiction,...,2681982.0,enk,0.89,3202759,1878,NaN,The devil's advocate,368,1878.0,1870.0
nyp/334/33075994578,-0.860179,hathi_englit|nyp/334/33075994578,"Chapone,",HathiEngLit,1778,s,,1.000,v. 1,Fiction,...,37989466.0,enk,0.53,8682060,1778,Conduct of life;Women,Letters on the improvement of the mind,210,1778.0,1770.0
hvd/hn2/he1,-0.875995,hathi_englit|hvd/hn2/he1,"Lambert, Anne Thérèse de Marguenat de Courcelles,",HathiEngLit,1800,s,,1.000,NaN,Fiction,...,3250382.0,enk,0.73,9712310,1800,Etiquette for children and teenagers;Juvenile ...,A mother's advice to her son and daughter,220,1800.0,1800.0
wu/890/97121669,-0.921061,hathi_englit|wu/890/97121669,"Jones, Lloyd,",HathiEngLit,1837,s,,0.999,NaN,Drama,...,37515422.0,enk,0.67,6854358,1837,"Book of the new moral world;1771-1858;Carlile,...",A reply to Mr. R. Carlile's objections to the ...,74,1837.0,1830.0
njp/321/01067015907,-0.934101,hathi_englit|njp/321/01067015907,"Cleveland, Grover,",HathiEngLit,1896,s,,0.995,NaN,Drama,...,27281118.0,dcu,0.77,5626242,1896,Universities and colleges,"Speech of Grover Cleveland, president of the U...",76,1896.0,1890.0

In [11]:
odf.genre.value_counts()

genre
Drama      17561
Fiction    11341
Poetry       439
Name: count, dtype: int64

In [12]:
odf.to_pickle('../../data/scores/v3/data.scores.HathiEngLit.pkl')